no_report_homepage:
    path:     /report/
    defaults: { _controller: NOReportBundle:Default:index }


no_admin_company_report:
    path:     /admin/comp/report/{companyId}
    defaults: { _controller: NOReportBundle:Default:adminCompanyReport }




