<?php

namespace NOThreatBundle\Repository;

/**
 * EventThreatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventThreatRepository extends \Doctrine\ORM\EntityRepository
{
}
