<?php

namespace NOThreatBundle\Repository;

/**
 * ThreatFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreatFamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
