<?php

namespace NOThreatBundle\Repository;

/**
 * ThreatSubFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreatSubFamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
