<?php

namespace CompanyBundle\Repository;

/**
 * ActivityBranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityBranchRepository extends \Doctrine\ORM\EntityRepository
{
}
