<?php

namespace CompanyBundle\Repository;

/**
 * CategMatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategMatriceRepository extends \Doctrine\ORM\EntityRepository
{
}
