<?php

namespace CompanyBundle\Repository;

/**
 * CodeNAFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeNAFRepository extends \Doctrine\ORM\EntityRepository
{
}
