<?php

namespace CompanyBundle\Repository;

/**
 * LegalStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
