<?php

namespace NOMatriceBundle\Repository;

/**
 * EcologicalMatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcologicalMatriceRepository extends \Doctrine\ORM\EntityRepository
{
}
