<?php

namespace NOMatriceBundle\Repository;

/**
 * EconomicalMatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EconomicalMatriceRepository extends \Doctrine\ORM\EntityRepository
{
}
