<?php

namespace NOMatriceBundle\Repository;

/**
 * LegalMatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalMatriceRepository extends \Doctrine\ORM\EntityRepository
{
}
