<?php

namespace NOMatriceBundle\Repository;

/**
 * MatriceBilanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriceBilanRepository extends \Doctrine\ORM\EntityRepository
{
}
