<?php

namespace NOMatriceBundle\Repository;

/**
 * PoliticalMatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoliticalMatriceRepository extends \Doctrine\ORM\EntityRepository
{
}
