<?php

namespace NOMatriceBundle\Repository;

/**
 * SocioCulturalMatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocioCulturalMatriceRepository extends \Doctrine\ORM\EntityRepository
{
}
