<?php

namespace NOMatriceBundle\Repository;

/**
 * TechnologicalMatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnologicalMatriceRepository extends \Doctrine\ORM\EntityRepository
{
}
