<?php

namespace NODiagBundle\Repository;

/**
 * CompanyQuestionSubFamilyAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyQuestionSubFamilyAccessRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCAR($compId, $subFamId){
		$qb = $this->createQueryBuilder('c');
		$qb->select('c');
		$qb->where('c.questionSubFamily = :sub');
		$qb->andWhere('c.company = :comp ');
		$qb->setParameter('comp',$compId);
		$qb->setParameter('sub',$subFamId);

		return $qb->getQuery()->getOneOrNullResult();

	}



}
