<?php

namespace NODiagBundle\Repository;

/**
 * ModeratorAccessRightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeratorAccessRightRepository extends \Doctrine\ORM\EntityRepository
{
	public function findMAR($moderatorId, $subFamId){
		$qb = $this->createQueryBuilder('m');
		$qb->select('m');
		$qb->where('m.questionSubFamily = :sub');
		$qb->andWhere('m.moderator = :mod ');
		$qb->setParameter('mod',$moderatorId);
		$qb->setParameter('sub',$subFamId);

		return $qb->getQuery()->getOneOrNullResult();

	}

	
}
