<?php

namespace NODiagBundle\Repository;

/**
 * QuestionSubFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionSubFamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
