<?php

namespace NODiagBundle\Repository;

/**
 * QuestionFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionFamilyRepository extends \Doctrine\ORM\EntityRepository
{
	
}
