<?php

namespace NODiagBundle\Repository;

/**
 * ResponseQuestionCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseQuestionCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
