<?php

namespace NODiagBundle\Repository;

/**
 * ResponseQuestionCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseQuestionCompanyRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCSFResponses($companyId,$subFamId){
		$qb  = $this->_em->createQueryBuilder();
		$res = $qb->select('r')
             ->from('NODiagBundle:ResponseQuestionCompany', 'r')
             ->innerJoin('r.question','q')
             ->innerJoin('q.subFamily','s')
             ->where('r.company = :comp')
             ->andWhere('s.id = :sub')
             ->setParameter('comp',$companyId)
             ->setParameter('sub',$subFamId)
             ->getQuery()
             ->getResult();
        return $res;
	}
}
